/*

@license
dhtmlxScheduler v.5.3.4 Professional Evaluation

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) XB Software Ltd.

*/
Scheduler.plugin(function(e){!function(){e._inited_multisection_copies||(e.attachEvent("onEventIdChange",function(e,t){var a=this._multisection_copies;if(a&&a[e]&&!a[t]){var i=a[e];delete a[e],a[t]=i}}),e._inited_multisection_copies=!0),e._register_copies_array=function(e){for(var t=0;t<e.length;t++)this._register_copy(e[t])},e._register_copy=function(e){if(this._multisection_copies){this._multisection_copies[e.id]||(this._multisection_copies[e.id]={});var t=e[this._get_section_property()]
;this._multisection_copies[e.id][t]=e}},e._get_copied_event=function(t,a){if(!this._multisection_copies[t])return null;if(this._multisection_copies[t][a])return this._multisection_copies[t][a];var i=this._multisection_copies[t];if(e._drag_event&&e._drag_event._orig_section&&i[e._drag_event._orig_section])return i[e._drag_event._orig_section];var n=1/0,r=null;for(var o in i)i[o]._sorder<n&&(r=i[o],n=i[o]._sorder);return r},e._clear_copied_events=function(){this._multisection_copies={}},
e._restore_render_flags=function(t){for(var a=this._get_section_property(),i=0;i<t.length;i++){var n=t[i],r=e._get_copied_event(n.id,n[a]);if(r)for(var o in r)0===o.indexOf("_")&&(n[o]=r[o])}};var t=e.createTimelineView;e.createTimelineView=function(a){function i(){var t=new Date(e.getState().date),i=e.date[c+"_start"](t);i=e.date.date_part(i);var n=[],r=e.matrix[c];r.y_unit=n,r.order={};for(var o=0;o<a.days;o++)n.push({key:+i,label:i}),r.order[r.y_unit[o].key]=o,i=e.date.add(i,1,"day")}
function n(e){var t={};for(var a in e)t[a]=e[a];return t}function r(e,t){t.setDate(1),t.setFullYear(e.getFullYear()),t.setMonth(e.getMonth()),t.setDate(e.getDate())}function o(t){for(var a=[],i=0;i<t.length;i++){var n=d(t[i]);if(e.isOneDayEvent(n))_(n),a.push(n);else{for(var r=new Date(Math.min(+n.end_date,+e._max_date)),o=new Date(Math.max(+n.start_date,+e._min_date)),l=[];+o<+r;){var c=d(n);c.start_date=o,c.end_date=new Date(Math.min(+h(c.start_date),+r)),o=h(o),_(c),a.push(c),l.push(c)}s(l,n)
}}return a}function s(e,t){for(var a=!1,i=!1,n=0,r=e.length;n<r;n++){var o=e[n];a=+o._w_start_date==+t.start_date,i=+o._w_end_date==+t.end_date,o._no_resize_start=o._no_resize_end=!0,a&&(o._no_resize_start=!1),i&&(o._no_resize_end=!1)}}function d(t){var a=e.getEvent(t.event_pid);return a&&a.isPrototypeOf(t)?(t=e._copy_event(t),delete t.event_length,delete t.event_pid,delete t.rec_pattern,delete t.rec_type):t=e._lame_clone(t),t}function _(t){if(!t._w_start_date||!t._w_end_date){
var a=e.date,i=t._w_start_date=new Date(t.start_date),n=t._w_end_date=new Date(t.end_date);t[u]=+a.date_part(t.start_date),t._count||(t._count=1),t._sorder||(t._sorder=0);var r=n-i;t.start_date=new Date(e._min_date),l(i,t.start_date),t.end_date=new Date(+t.start_date+r),i.getTimezoneOffset()!=n.getTimezoneOffset()&&(t.end_date=new Date(t.end_date.valueOf()+6e4*(i.getTimezoneOffset()-n.getTimezoneOffset())))}}function l(e,t){t.setMinutes(e.getMinutes()),t.setHours(e.getHours())}function h(t){
var a=e.date.add(t,1,"day");return a=e.date.date_part(a)}if("days"!=a.render)return void t.apply(this,arguments);var c=a.name,u=a.y_property="timeline-week"+c;a.y_unit=[],a.render="bar",a.days=a.days||7,t.call(this,a),e.templates[c+"_scalex_class"]=function(){},e.templates[c+"_scaley_class"]=function(){},e.templates[c+"_scale_label"]=function(t,a,i){return e.templates.day_date(a)},e.date[c+"_start"]=function(t){return t=e.date.week_start(t),t=e.date.add(t,a.x_step*a.x_start,a.x_unit)},
e.date["add_"+c]=function(t,i){return e.date.add(t,i*a.days,"day")};var g=e._renderMatrix;e._renderMatrix=function(e,t){e&&i(),g.apply(this,arguments)};var f=e.checkCollision;e.checkCollision=function(t){if(t[u]){var t=n(t);delete t[u]}return f.apply(e,[t])},e.attachEvent("onBeforeDrag",function(t,a,i){var n=i.target||i.srcElement,r=e._getClassName(n)
;if("resize"==a)r.indexOf("dhx_event_resize_end")<0?e._w_line_drag_from_start=!0:e._w_line_drag_from_start=!1;else if("move"==a&&r.indexOf("no_drag_move")>=0)return!1;return!0});var v=e["mouse_"+c];e["mouse_"+c]=function(t){var a;this._drag_event&&(a=this._drag_event._move_delta);var i=e.matrix[this._mode];if(i.scrollable&&!t.converted&&(t.converted=1,t.x-=-i._x_scroll,t.y+=i._y_scroll),void 0===a&&"move"==e._drag_mode){var n={y:t.y};e._resolve_timeline_section(i,n)
;var r=t.x-i.dx,o=new Date(n.section);l(e._timeline_drag_date(i,r),o);var s=e._drag_event,d=this.getEvent(this._drag_id);d&&(s._move_delta=(d.start_date-o)/6e4,this.config.preserve_length&&t._ignores&&(s._move_delta=this._get_real_event_length(d.start_date,o,i),s._event_length=this._get_real_event_length(d.start_date,d.end_date,i)))}var t=v.apply(e,arguments);if(e._drag_mode&&"move"!=e._drag_mode){var _=null
;_=e._drag_event&&e._drag_event["timeline-week"+c]?new Date(e._drag_event["timeline-week"+c]):new Date(t.section),t.y+=Math.round((_-e.date.date_part(new Date(e._min_date)))/(6e4*this.config.time_step)),"resize"==e._drag_mode&&(t.resize_from_start=e._w_line_drag_from_start)}else if(e._drag_event){var h=Math.floor(Math.abs(t.y/(1440/e.config.time_step)));h*=t.y>0?1:-1,t.y=t.y%(1440/e.config.time_step);var u=e.date.date_part(new Date(e._min_date))
;u.valueOf()!=new Date(t.section).valueOf()&&(t.x=Math.floor((t.section-u)/864e5),t.x+=h)}return t},e.attachEvent("onEventCreated",function(t,a){return e._events[t]&&delete e._events[t][u],!0}),e.attachEvent("onBeforeEventChanged",function(t,a,i,n){return e._events[t.id]&&delete e._events[t.id][u],!0});var m=e._update_timeline_section;e._update_timeline_section=function(t){var a,i
;this._mode==c&&(a=t.event)&&(i=e._get_copied_event(a.id,e.date.day_start(new Date(a.start_date.valueOf()))))&&(t.event._sorder=i._sorder,t.event._count=i._count);m.apply(this,arguments);a&&i&&(i._count=a._count,i._sorder=a._sorder)};var p=e.render_view_data;e.render_view_data=function(t,a){return this._mode==c&&t&&(t=o(t),e._restore_render_flags(t)),p.apply(e,[t,a])};var x=e.get_visible_events;e.get_visible_events=function(){if(this._mode==c){this._clear_copied_events(),
e._max_date=e.date.date_part(e.date.add(e._min_date,a.days,"day"));var t=x.apply(e,arguments);return t=o(t),e._register_copies_array(t),t}return x.apply(e,arguments)};var b=e.addEventNow;e.addEventNow=function(t){if(e.getState().mode==c)if(t[u]){var a=new Date(t[u]);r(a,t.start_date),r(a,t.end_date)}else{var i=new Date(t.start_date);t[u]=+e.date.date_part(i)}return b.apply(e,arguments)};var y=e._render_marked_timespan;e._render_marked_timespan=function(){
if(e._mode!=c)return y.apply(this,arguments)}}}()});